# Generated by Django 2.0.4 on 2018-04-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAssert',
            fields=[
                ('assert_id', models.AutoField(primary_key=True, serialize=False)),
                ('assert_type', models.CharField(blank=True, max_length=20, null=True)),
                ('assert_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'admin_assert',
            },
        ),
        migrations.CreateModel(
            name='AdminnotificationInbox',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.PositiveSmallIntegerField()),
                ('date_added', models.DateTimeField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.PositiveSmallIntegerField()),
                ('is_remove', models.PositiveSmallIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'adminnotification_inbox',
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.PositiveIntegerField()),
                ('tree_level', models.PositiveSmallIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('role_type', models.CharField(max_length=1)),
                ('user_id', models.PositiveIntegerField()),
                ('role_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'admin_role',
            },
        ),
        migrations.CreateModel(
            name='AdminRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_id', models.CharField(blank=True, max_length=255, null=True)),
                ('privileges', models.CharField(blank=True, max_length=20, null=True)),
                ('assert_id', models.PositiveIntegerField()),
                ('role_type', models.CharField(blank=True, max_length=1, null=True)),
                ('permission', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'admin_rule',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=32, null=True)),
                ('lastname', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('logdate', models.DateTimeField(blank=True, null=True)),
                ('lognum', models.PositiveSmallIntegerField()),
                ('reload_acl_flag', models.SmallIntegerField()),
                ('is_active', models.SmallIntegerField()),
                ('extra', models.TextField(blank=True, null=True)),
                ('rp_token', models.TextField(blank=True, null=True)),
                ('rp_token_created_at', models.DateTimeField(blank=True, null=True)),
                ('customer_group_id', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'admin_user',
            },
        ),
    ]
